### ISSUE TITLE
Keystone 5 Roadmap Items from Keystone 4

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1002]
This issue is to collect Keystone 4 features or feature requests that are on the roadmap for v5. I'll keep the description updated when we put things in scope, and link to issues / tick them off when they're done.

----

- [ ] Custom actions, see keystonejs/keystone#2101
- [ ] Display related items on item details page
- [x] Markdown field type
- [ ] JSON field type
- [ ] Location field type
- [ ] Nested fields (may be better relationship management and/or block-based content field)
- [ ] Item History with UI and rollback
- [ ] Allow sorting of related items (for relationship fields, and related items), see keystonejs/keystone#441

**Comment by gautamsi** [comment]
Adding more
-[ ] Compatibility with v4 View Queries
-[ ] `keyston.populateRelated`
-[ ] `keystone.updateHandler`

I am proposing this as part of `v4-compat` package

**Comment by MadeByMike** [comment]
All of these have now been better captured with new issues
