### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1659]
This issue is to capture a range of tasks related to better handling of errors. Many of these are simply about either better capturing an error or providing more helpful error messages to users.

Many of these are related and could be fixed quickly if focusing on them together:

- [ ] Creating a slug 'from' a Relationship results in a confusing error error message fields #1655 
- [ ] GQL error text appearing twice bug error message #1615
- [ ] Show client side isRequired errors in admin ui admin-ui error message #1270
- [ ] Confusing error for unknown column in defaultColumns #1248 
- [ ] Improve error message when database connection fails #1243 
- [x] Errors thrown within field / field type hooks have incorrect `path` #1221 
- [ ] Password confirmation does not confirm password #1139
- [ ] Throw an error if keystone.connect not called before queries made #1081 
- [ ] Show validation/network errors in Create Item form #1074
- [ ] Surface isUnique constraint errors in Admin UI #433
- [ ] Errors thrown from hooks are not caught #1220
- [ ] Errors thrown from admin UI views should be caught and displayed #1224
- [ ] Scrub error message call stacks in production to avoid leaking information when errors occur.

**Comment by jesstelford** [comment]
- [ ] Scrub error message call stacks in production to avoid leaking information when errors occur.

**Comment by molomby** [comment]
> Scrub error message call stacks in production to avoid leaking information when errors occur.

Very this ^^^ but only in production, I'd say. Generally there should be different error behaviours when not in production. Ie. much more verbose, both to the logs and via the API.

**Comment by molomby** [comment]
See also #245 and #261

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
