### ISSUE TITLE
Feature wishlist

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1897]
## High priorities:
- [x] Universal Routing - will require an overhaul of how routing is currently handled.
- [x] React Universal rendering.
- [ ] Universal data bootstrapping. Now that Universal Routing and Rendering is complete, we need [a standard way to feed data into the component hierarchy](https://github.com/keystonejs/keystone/issues/2090) that works on both the client and server. (In-progress).
- [x] i18n language negotiation.
- [ ] i18n translation support (Needs discussion. See #802.)
- [ ] API enhancements - make it easier to work with custom fieldtypes. (See also: [restful-keystone](https://github.com/d-pac/restful-keystone)) - check authentication and authorization
- [ ] Content Workflows - Currently admin & content creation are not workflow focused.
- [ ] eCommerce plugin - think WooCommerce. At least simple out-of-the-box support for simple product pages that will be reused in virtually all eCommerce implementations. It's currently a very roll-your-own process, not reusing boilerplate & best practices.
## Lower priorities, but generally reusable for almost any Keystone app:
- [ ] Social signup
- [ ] Facebook Open Graph - Make pages look pretty on Facebook
- [ ] Twitter Cards - Make pages look pretty on Twitter
## Long Term Improvements & Plugins:
- [ ] WordPress-esque plugin architecture, admin, and search/install.
- [ ] Group memberships = add user to a specific group. A single user can have many group subscriptions.
- [ ] Paid user membership subscriptions. On checkout, add user to group for x days/months/year
- [ ] Authorize resource access by group membership. See [this comment](https://github.com/keystonejs/keystone/issues/803#issuecomment-168464839) for implementation ideas.
- [ ] Login with GitHub
- [ ] Login integration with Auth0
- [ ] Author content in MarkDown with code syntax highlighting & HTML embed support (Vimeo, YouTube, etc...)
- [ ] Support orgs & org members (similar to GitHub)
- [ ] Gitter & Slack chat integration
- [ ] Group meeting scheduler & video conference / webcast
- [ ] Audit logging

**Comment by ericelliott** [comment]
If there are other open issues for any of these features, let's reference them and coordinate. =)

**Comment by morenoh149** [comment]
* Plugin Architecture proposal https://github.com/keystonejs/keystone/issues/912
* Groups/acl https://github.com/keystonejs/keystone/issues/803
* We already have markdown http://keystonejs.com/docs/database/#fieldtypes-markdown but not with syntax highlighting or html embed support. Related issue https://github.com/keystonejs/keystone/issues/1892
* for logins we have historically told users to use passport.js

**Comment by ericelliott** [comment]
I've had a better chance to get a handle on priorities for the projects I'm working on. Feedback welcome! =)

**Comment by cantuket** [comment]
One thing that I seem to be hacking quite often is just a 'static page' model. Basically defining a model as a single item so you never have a List, only a single Item that comes up immediately.

My users get confused when I have a 'Home Page' model then the have to click on the 'Home Page' item in that list to edit the content. Seems like it might be fairly easy to implement too?

**Comment by cantuket** [comment]
A somewhat crazy idea I've been working on is a pre-compiling feature for pages/sections that are updated fairly irregularly (Home Page, Navs, Footer etc.). I'm compiling my Jade and using fs.write() to create/re-write static HTML pages based off my models every time they are updated. I got stuck when trying to make my routes reflect the static file system in a scalable and sane way.

Just trying to push load-time to its max and get the database calls out of the way when they aren't necessary.

**Comment by ericelliott** [comment]
:+1: pre-rendered routes are a good idea.

**Comment by niallobrien** [comment]
I think it's worth adding *Securing REST API endpoints* to the *API enhancements* task.

**Comment by lilbitsboo** [comment]
Hey , 
I'm thinking about implementing an bootstrap carousel plugin for tinyMCE  , and then integrate it into keystone , does anyone has ideas/working on a same thing / wants to buy me coffee ?

**Comment by VinayaSathyanarayana** [comment]
pre-rendered routes is really good idea. May be we can have a flag in every list that says it is rarely updated and hence can be cached / pre compiled

**Comment by kadosh1000** [comment]
Hi I have published my npm package: 
https://github.com/kadosh1000/keystone-custom-fieldtypes

It copies your custom fieldTypes from a selected dir into the keystone's fields dir and registers it

**Comment by mxstbr** [comment]
Should be added maybe, this wysiwyg cms idea is pretty awesome: #2274

**Comment by Noviny** [comment]
Closed as we are not referencing this anymore. It is not a good representation of our roadmap.
