### ISSUE TITLE
Add all core field types

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone#19]
Capturing this information here from a discussion around it. There is a set of field-types that are basic enough that we would want to build them as part of a base set, before starting to look at more complex field types. This list should be seen as a starting point:

- [x] Boolean (checkbox): See issue #146 @mikehazell
- [x] Date
- [x] Date-time
- [x] date-time-timezone
- [x] Number (double, integer, decimal, likely want them all)
    - [x] Float: See issue #148 @mikehazell
    - [x] Int: See issue #150 @mikehazell
- [x] Id (relationship)
- [x] Password
- [x] Select
- [x] Text

Other types that were brought up:
- [ ] list type (nested lists)
- [ ] text-area
- [ ] geo
