### ISSUE TITLE
Arch (KS UI Kit): initial site, docs, etc.

### ISSUE THREAD

**Issue by jossmac** [keystonejs/keystone#225]
<img src="https://user-images.githubusercontent.com/2730833/44125742-989cd9ee-a077-11e8-93ef-fc55b29cebdf.png" alt="Arch Logo" width="173" height="146" align="right" />

# Arch

Keystone's UI Kit / Design Language needs a home and documentation.

#### Technology

- [bolt](http://boltpkg.com/)
- [gatsby](https://www.gatsbyjs.org/)
- [graphql](https://graphql.org/)

#### TODO

- [ ] site design / content architecture
- [ ] create monorepo
- [ ] move individual components from keystone-5 to `packages/{PKG_NAME}` with `README.md`
- [ ] setup gatsby to render readme files as docs via graphql
- [ ] find solution for dynamic doc navigation and toc creation

#### Inspiration

- https://styleguide.github.com/
- https://ant.design/
- http://www.carbondesignsystem.com/
- https://www.gatsbyjs.org/
- https://reactjs.org/

**Comment by gautamsi** [comment]
Would this be helpful to use storybook to showcase `arch-ui` components?

**Comment by MadeByMike** [comment]
@gautamsi I think the plan is to rename arch-ui to keystone-ui and use [docz](https://www.docz.site/). It's not something we are going to get to soon so if you are interested in doing this I would definitely welcome PRs. 👍

**Comment by mitchellhamilton** [comment]
Important note: The plan is to only rename keystone-ui once we refactor arch-ui a bunch and properly decide what should exist there and what shouldn't.

**Comment by gautamsi** [comment]
I will try to add docz support and not rename anything now.  

may still be good to have `arch-ui` name.

**Comment by MadeByMike** [comment]
We're moving away from Arch in future.

**Comment by MadeByMike** [comment]
For context: The plan, eventually is to have a UI library/design system (probably elemental) that underpins Keystone. This probably will not be an immediate thing and will happen gradually as we improve the adminUI and less gradually if we eventually make that leap of refactoring onto a different platform (I don't think that will happen soon)

Regardless of the above I think it is safe to say that there are no intentions currently to further promote archUI
