### ISSUE TITLE
Missing e2e test coverage

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3968]
This issue to it track all missing e2e tests. Currently, our test suite is missing quite a lot, and issues which should be caught are slipping through. Currently, most fields undergo a standard set of tests, where the field is simply filled with some test value. However, we should also check validation and other config options are working as intended. 

Since we don't always have the time to add tests, we should keep this list up to date, so that when we do have time to work on it, we know exactly what needs doing. 

As new issues are logged, they should all be evaluated as to whether they should have been caught by e2e, and if so they should be added to this list. 

Some of the items in this list may require changes on the keystone-nightwatch-e2e issue. If so, there is a corresponding issue there to add them to, and issues here should be marked with (depends on KNE) in the list.

Missing functionality:

- [ ] Html fields with `wysiwyg: true` (depends on KNE)

Fields which are not tested:

- [ ] File fields are not tested
- [ ] Cloudinary fields are not tested
