### ISSUE TITLE
Customize Algolia Search UI to better match website design

### ISSUE THREAD

**Issue by raveling** [keystonejs/keystone#6295]
Algolia's default search UI isn't a snug fit with the rest of the site design. A few small changes to CSS could make it better.

![CleanShot 2021-08-11 at 09 31 00](https://user-images.githubusercontent.com/6447754/128947852-4351db5a-d5c5-4239-b0d0-9dc15a007d94.png)

**TODO:** (adapted from https://github.com/keystonejs/keystone/pull/6052)

- [ ] Add search support in mobile
- [ ] Dark mode (requires adjusting base Algolia styles and adding variables
- [ ] Search box border in Chromium browsers
<img width="486" alt="Screen Shot 2021-07-02 at 2 17 53 pm" src="https://user-images.githubusercontent.com/737821/124224876-cfc7b780-db49-11eb-96de-0fce850ca111.png">

- [ ] Adjust dropdown styles to match website
- [ ] Avoid indices pages like /docs/guides so results go direct to unique stuff (instead of cards)
![CleanShot 2021-07-02 at 12 13 57](https://user-images.githubusercontent.com/737821/124219050-db61b100-db3e-11eb-939b-75a628aba1c2.png)
- [ ] Provide context based on the parent folder of the indexed record (most likely requires config adjustment on Algolia's side)
![CleanShot 2021-07-02 at 12 16 18](https://user-images.githubusercontent.com/737821/124219054-ddc40b00-db3e-11eb-9a0f-734d9ce5ae89.png)

**Comment by bladey** [comment]
Added comments from PR https://github.com/keystonejs/keystone/pull/6052 to close it.

**Comment by bladey** [comment]
Moved to planning docs.
