### ISSUE TITLE
Rearchitect view packages ready for production use (and serverless)

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#734]
**Goals**:
- To deploy KS5 to serverless
- Reduce dependency sizes when only using some types (eg; the TODO example pulls in all the things but only uses `Text`

**Challenges**:
- Serverless is not always a full node env, so some deps (and hence types) can't be fully required
- Field `views` need to be compiled (flow + JSX) in published packages

**Proposal**
- Move each field type to its own package (eg; `@vooswah/field-text` / `@vouswar/field-password`)
- Change the `view` paths (currently using `require.resolve`) within each field to be actual packages that the admin UI can import/require (eg; `@vorswaa/admin-view-text` / `@vhooswoi/admin-view-password`)
- Use `preconstruct` to build those `admin-view-*` packages (like we do for the `arch-ui` package currently)

### TODO

- [ ] Port a single type to this structure to test it out
  - [ ] Update `field-views-loader` to handle new packages
- [ ] Port all existing types to new structure
- [ ] Build views with `preconstruct`
- [ ] Compile fields with babel (can `preconstruct` do this?)
- [ ] Test it all works with `@zeit/ncc` (lambda compiler) without error
- [ ] Port `Content` `block`s to a similar structure
- [ ] Add support for the `extendViews` mechanism `Content` `block`s rely on
- [ ] Update demo projects
- [ ] Update tests
- [ ] Update docs
- [ ] Publish all new types

**Comment by w01fgang** [comment]
Admin UI doesn't need SSR, that's for sure. Usually, SSR is needed for the front-end to make it SEO friendly.
Next.js works perfectly in a serverless environment. Many people make a huge bet on serverless, for example, Zeit will deprecate server environment making Now v2 completely serverless.

It would be great to have:
- Serverless API
- Serverless render of the frontend with next.js
- Static admin panel

As I understood, admin UI in production already static, right?
Maybe KS5 already works in a serverless environment, maybe we just need to make an example of how to handle requests directly without `express`.
